version: 2
jobs:
  build:
    working_directory: ~/repo/release-history-api
    docker:
      - image: circleci/golang:1.12-stretch
    steps:
      - checkout
      - run:
          name: Adding go bins to path
          command: |
            echo 'export PATH=$PATH:$GOPATH/bin' >> $BASH_ENV
      - run:
          name: Building
          command: |
            go build
      - run:
          name: Running tests
          command: |
            go test ./...
  docker_and_deploy:
    working_directory: ~/repo/release-history-api
    docker:
      - image: circleci/golang:1.12-stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Adding docker configuration
          command: |
            cat > ~/.dockercfg << EOF
            {
                "https://index.docker.io/v1/": {
                    "auth": "$DOCKER_AUTH",
                    "email": "$DOCKER_EMAIL"
                }
            }
            EOF
      - run:
          name: Adding environment variables
          command: |
            echo 'export TAG=$CIRCLE_BRANCH-$CIRCLE_SHA1' >> $BASH_ENV
            echo 'export DOCKER_IMAGE=applift/release-history-api:$TAG' >> $BASH_ENV
      - run: echo "DOCKER_IMAGE is $DOCKER_IMAGE"
      - run: docker build -t $DOCKER_IMAGE .
      - run: echo "Starting push $DOCKER_IMAGE"
      - run: |
          if [[ $CIRCLE_BRANCH == master ]] || [[ $CIRCLE_BRANCH == automatic-* ]]; then
            echo "Starting push $DOCKER_IMAGE"
            docker push $DOCKER_IMAGE
          fi
      - run: |
          if [[ $CIRCLE_BRANCH == master ]]
          then
            echo "Deploy release history api (TODO)"
          fi

workflows:
  version: 2
  build_docker_and_deploy:
    jobs:
      - build
      - docker_and_deploy:
          requires:
            - build
