version: '2.1'

services:

  release-history-api:
    image: release-history-api
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_CONNECTION_STRING: "postgres://releasehistory:releasehistorylocal@postgres:5432/releasehistory?sslmode=disable"

  postgres:
    image: release-history-api-postgres
    build:
      context: docker/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
